name: Empaquetar main despois de tests
on:
  workflow_dispatch:
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out del repositorio
        uses: actions/checkout@v6
      - run: python -m unittest test_utils.py
  Main:
    runs-on: ubuntu-latest
    needs: Tests
    steps:
      - name: Crear entorno virtual
      - run: python3 -m venv .venv && source .venv/bin/activate
      - name: Empaquetar main.py
      - run: pip install pyinstaller && pyinstaller --onefile main.py
      - name: Proba execucións
      - run: ./dist/main 4 && ./dist/main 1
      - name: Subir artefacto
      - uses: actions/upload-artifact@v7
        with:
          name: ./dist/main
          archive: false
