name: Empaquetar main despois de tests
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out del repositorio
        uses: actions/checkout@v6
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'         
      - run: python -m unittest test_utils.py
  Main:
    runs-on: ubuntu-latest
    needs: Tests
    if: success()
    steps:
      - name: Check out del repositorio
        uses: actions/checkout@v6
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'          
      - name: Empaquetar main.py
        run: pip install pyinstaller && pyinstaller --onefile main.py
      - name: Proba execucións
        run: ./dist/main 4 && ./dist/main 1
      - name: Subir artefacto
        uses: actions/upload-artifact@v7
        with:
          name: executable
          path: ./dist/main
          archive: false
